CREATE DATABASE IF NOT EXISTS titangym;
USE titangym;

CREATE TABLE IF NOT EXISTS clientes (
  Id BIGINT AUTO_INCREMENT PRIMARY KEY,
  DNI INT NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  Apellido VARCHAR(100) NOT NULL,
  Direccion VARCHAR(200),
  Telefono VARCHAR(50),
  Correo VARCHAR(100),
  Fecha_Alta DATETIME DEFAULT CURRENT_TIMESTAMP,
  Activo BOOLEAN DEFAULT true
);